---
title: "hs-zs.statistical report"
author: "xvyingrui"
date: "2018年2月6日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




#统计分析报告
一、读入已经统计好统计量的两家医院的结果
二、合并两家医院对照组和实验组的统计结果
三、进行单因素分析求均值、标准差等统计量，并做假设检验
四、进行多因素分析，建立多元线性回归方程
################################################

#准备需要的包和描述性统计函数
```{r}
library(tidyverse)
library(knitr)
library(broom)
mystats<-function(x,na.omit=FALSE){
    y=sum(is.na(x))
    if(na.omit)
        x<-x[!is.na(x)]
    l=length(x)
    m<-round(mean(x),4)
    n<-round(sd(x),4)
    o<-round(median(x),4)
    p<-round(quantile(x,0.25),4)
    q<-round(quantile(x,0.75),4)
    r<-round(min(x),4)
    s<-round(max(x),4)
    t<-round(length(which(x==0)),4)
    u<-round(length(which(x>0)),4)
    return(c(n=l,缺失值=y,mean=m,sd=n,median=o,median1=p,
             median3=q,min=r,max=s,等于0的个数=t,大于0的个数=u))
}

```
一、导入数据
```{r}
hs.dz=read.csv("h:/data/gaoyue1221合并/0205/华山对照组0205.csv")
hs.sy=read.csv("h:/data/gaoyue1221合并/0205/华山实验组0205.csv")
zs.dz=read.csv("h:/data/gaoyue1221合并/0205/中山对照组0205.csv")
zs.sy=read.csv("h:/data/gaoyue1221合并/0205/中山实验组0205.csv")
```

1、先对实验组进行处理、统计

```{r}
#查看实验组数据的名字
cbind(kable(names(hs.sy)),kable(names(zs.sy)))%>%as.data.frame()

```

```{r}
#整理中山医院实验组的变量
zs.sy$end_start1=ifelse(zs.sy$end_start1<1,1,zs.sy$end_start1)
zs.sy1=zs.sy%>%
  rename(ID=门诊号,age1=age)%>%
  mutate(一年心血管次数=门诊心血管次数+住院心血管次数,
                门诊加住院所有心血管次数=门诊所有时间心血管次数+住院所有时间心血管次数,
                门诊发生频率=门诊所有时间心血管次数/end_start1,
                总发生频率=(门诊所有时间心血管次数+住院所有时间心血管次数)/end_start1,
                门诊加住院费用=门诊费用+住院费用,
                心血管资源门诊加住院费用=心血管资源门诊费用+心血管资源住院费用,
                age=rep(9999,nrow(zs.sy)))%>%
  select(-c(住院药品费用,住院非药品费用,心血管资源住院药品费用,心血管资源非药品费用))
str(zs.sy1)
```

```{r}
#整理华山医院实验组的
hs.sy$end_start1=ifelse(hs.sy$end_start1<1,1,hs.sy$end_start1)
hs.sy1=hs.sy%>%
  rename(门诊所有时间心血管次数=门诊所有心血管次数,住院所有时间心血管次数=住院所有心血管次数,
                    性别=MAX.DECODE.E.XINGB.0..男...女.,age=MAX.SENGR.,保险类别=MAX.DECODE.E.JZFSM..1...自费..,
                    科室名称=MAX.DEPTNAME.,心血管资源门诊费用=门诊心血管资源费用)
hs.sy1$age1=2017-as.numeric(substr(hs.sy1$age,1,4))
hs.sy1$一年心血管次数=hs.sy1$门诊心血管次数+hs.sy1$住院心血管次数
hs.sy1$门诊加住院费用=hs.sy1$门诊费用+hs.sy1$住院费用
hs.sy1$心血管资源门诊加住院费用=hs.sy1$心血管资源门诊费用+hs.sy1$心血管资源住院费用
str(hs.sy1)

```

```{r}
#合并中山华山实验组统计结果
zs.hs.sy=rbind(zs.sy1,hs.sy1)
zs.hs.sy=zs.hs.sy[,-26]
str(zs.hs.sy)
#查看是否有缺失值
kable(sapply(zs.hs.sy,function(x){sum(is.na(x))}))

#连续变量的统计
lapply(zs.hs.sy[,c(5:15,19:25)],function(x){mystats(x)})%>%as.data.frame.list()%>%t()%>%kable()
#分类变量的统计
sum(zs.hs.sy[,"age1"]<60)
sum(zs.hs.sy[,"age1"]<60)/nrow(zs.hs.sy)
sum(zs.hs.sy[,"age1"]>=60)
sum(zs.hs.sy[,"age1"]>=60)/nrow(zs.hs.sy)

kable(table(zs.hs.sy$性别)%>%as.data.frame()%>%mutate(占比=round(Freq/sum(Freq),4)))
kable(table(zs.hs.sy$科室名称)%>%as.data.frame()%>%mutate(占比=round(Freq/sum(Freq),4))%>%arrange(desc(占比)))
kable(table(zs.hs.sy$保险类别)%>%as.data.frame()%>%mutate(占比=round(Freq/sum(Freq),4))%>%arrange(desc(占比)))
```

2、对对照组进行处理、统计

```{r}
#查看实验组数据的名字
cbind(kable(names(hs.dz)),kable(names(zs.dz)))%>%as.data.frame()

```

```{r}
#整理华山医院对照组
hs.dz$end_start1=ifelse(hs.dz$end_start1<1,1,hs.dz$end_start1)
hs.dz1=hs.dz%>%
  rename(门诊所有时间心血管次数=门诊所有心血管次数,住院所有时间心血管次数=住院所有心血管次数,
                    性别=MAX.DECODE.E.XINGB.0..男...女.,age=MAX.SENGR.,保险类别=MAX.DECODE.E.JZFSM..1...自费..,
                    科室名称=MAX.DEPTNAME.,门诊费用=门诊总费用,ID=门诊号)%>%
  mutate(一年心血管次数=门诊心血管次数+住院心血管次数,
                门诊加住院所有心血管次数=门诊所有时间心血管次数+住院所有时间心血管次数)
hs.dz1$age1=2017-as.numeric(substr(hs.dz1$age,1,4))
hs.dz1=hs.dz1%>%select(-c(MEDCARD,CURENO,age,门诊费用1,门诊费用2))


#整理中山医院对照组
zs.dz$end_start1=ifelse(zs.dz$end_start1<1,1,zs.dz$end_start1)
zs.dz1=zs.dz%>%
  rename(age1=age,ID=门诊号)%>%
  mutate(门诊加住院总费用=门诊费用+住院费用,心血管资源门诊加住院总费用=心血管资源门诊费用+心血管资源住院费用,
                 门诊发生频率=门诊所有时间心血管次数/end_start1,
                 总发生频率=(门诊所有时间心血管次数+住院所有时间心血管次数)/end_start1,
                 一年心血管次数=门诊心血管次数+住院心血管次数,
                 门诊加住院所有心血管次数=门诊所有时间心血管次数+住院所有时间心血管次数)%>%
  select(-c(住院药品费用,住院非药品费用,心血管资源住院药品费用,心血管资源非药品费用))

cbind(kable(names(hs.dz1)),kable(names(zs.dz1)))%>%as.data.frame()

```

```{r}
#合并对照组结果
zs.hs.dz=rbind(zs.dz1,hs.dz1)
zs.hs.dz=rename(zs.hs.dz,门诊加住院费用=门诊加住院总费用,心血管资源门诊加住院费用=心血管资源门诊加住院总费用)
str(zs.hs.dz)
#查看是否有缺失值
kable(sapply(zs.hs.dz,function(x){sum(is.na(x))}))
#missing filling
zs.hs.dz[is.na(zs.hs.dz)]<-0
kable(sapply(zs.hs.dz,function(x){sum(is.na(x))}))

#连续变量的统计
lapply(zs.hs.dz[,c(5:15,19:25)],function(x){mystats(x)})%>%as.data.frame.list()%>%t()%>%kable()


#分类变量的统计
sum(zs.hs.dz[,"age1"]<60)
sum(zs.hs.dz[,"age1"]<60)/nrow(zs.hs.dz)
sum(zs.hs.dz[,"age1"]>=60)
sum(zs.hs.dz[,"age1"]>=60)/nrow(zs.hs.dz)

kable(table(zs.hs.dz$性别)%>%as.data.frame()%>%mutate(占比=round(Freq/sum(Freq),4)))
kable(table(zs.hs.dz$科室名称)%>%as.data.frame()%>%mutate(占比=round(Freq/sum(Freq),4))%>%arrange(desc(占比)))
kable(table(zs.hs.dz$保险类别)%>%as.data.frame()%>%mutate(占比=round(Freq/sum(Freq),4))%>%arrange(desc(占比)))

```


二、单因素分析

```{r}
#zs.hs.dz
#zs.hs.sy
kable(data.frame(colnames(zs.hs.sy),colnames(zs.hs.dz)))

t.test(zs.hs.sy$门诊次数,zs.hs.dz$门诊次数)%>%tidy()%>%t()%>%kable(col.names ="门诊次数")
t.test(zs.hs.sy$门诊心血管次数,zs.hs.dz$门诊心血管次数)%>%tidy()%>%t()%>%kable(col.names ="门诊心血管次数")
t.test(zs.hs.sy$门诊所有时间心血管次数,zs.hs.dz$门诊所有时间心血管次数)%>%tidy()%>%t()%>%kable(col.names ="门诊所有时间心血管次数")
t.test(zs.hs.sy$住院次数,zs.hs.dz$住院次数)%>%tidy()%>%t()%>%kable(col.names ="住院次数")
t.test(zs.hs.sy$住院心血管次数,zs.hs.dz$住院心血管次数)%>%tidy()%>%t()%>%kable(col.names ="住院心血管次数")
t.test(zs.hs.sy$住院天数,zs.hs.dz$住院天数)%>%tidy()%>%t()%>%kable(col.names ="住院天数")
t.test(zs.hs.sy$住院所有时间心血管次数,zs.hs.dz$住院所有时间心血管次数)%>%tidy()%>%t()%>%kable(col.names ="住院所有时间心血管次数")
t.test(zs.hs.sy$门诊费用,zs.hs.dz$门诊费用)%>%tidy()%>%t()%>%kable(col.names ="门诊费用")
t.test(zs.hs.sy$住院费用,zs.hs.dz$住院费用)%>%tidy()%>%t()%>%kable(col.names ="住院费用")
t.test(zs.hs.sy$心血管资源门诊费用,zs.hs.dz$心血管资源门诊费用)%>%tidy()%>%t()%>%kable(col.names = "心血管资源门诊费用")
t.test(zs.hs.sy$心血管资源住院费用,zs.hs.dz$心血管资源住院费用)%>%tidy()%>%t()%>%kable(col.names ="心血管资源住院费用")
t.test(zs.hs.sy$age1,zs.hs.dz$age1)%>%tidy()%>%t()%>%kable(col.names ="age1")
t.test(zs.hs.sy$一年心血管次数,zs.hs.dz$一年心血管次数)%>%tidy()%>%t()%>%kable(col.names ="一年心血管次数")
t.test(zs.hs.sy$门诊加住院所有心血管次数,zs.hs.dz$门诊加住院所有心血管次数)%>%tidy()%>%t()%>%kable(col.names ="门诊加住院所有心血管次数")
t.test(zs.hs.sy$门诊发生频率,zs.hs.dz$门诊发生频率)%>%tidy()%>%t()%>%kable(col.names ="门诊发生频率")
t.test(zs.hs.sy$总发生频率,zs.hs.dz$总发生频率)%>%tidy()%>%t()%>%kable(col.names ="总发生频率")
t.test(zs.hs.sy$门诊加住院费用,zs.hs.dz$门诊加住院费用)%>%tidy()%>%t()%>%kable(col.names ="门诊加住院费用")
t.test(zs.hs.sy$心血管资源门诊加住院费用,zs.hs.dz$心血管资源门诊加住院费用)%>%tidy()%>%t()%>%kable(col.names ='心血管资源门诊加住院费用')


#obj3
#age--60
obj3.age60=data.frame(a=c(38,401),b=c(368,1480))
chisq.test(obj3.age60)

#gender
obj3.gender=data.frame(a=c(190,968),b=c(249,880))
chisq.test(obj3.gender)


#发生住院次数
obj3.zycs=data.frame(a=c(360,1695),b=c(79,153))
chisq.test(obj3.zycs)

#发生心血管住院次数
obj3.zycs=data.frame(a=c(379,1740),b=c(60,108))
chisq.test(obj3.zycs)

#obj3保险类别卡方

c1=c(301,47,46,30,14,1)
c2=c(800,52,546,272,175,3)
c3=rbind(c1,c2)
chisq.test(c3)



```














